### ISSUE TITLE
MMOItems Crafting Stations integration

### ISSUE THREAD

**Issue by ShadySt** [Xiao-MoMi/Custom-Fishing#10]
Hi!
I'm trying to use custom fish in MMOItems Crafting Stations recipes. Couldn't find any useful information on wiki, is it even possible?
I have enabled option in config.yml for MMOItems integration. 
Could you please define, how should I specify in recipes for MMOItems items from your plugins?
For example, that's how you specify vanilla or items from mmoitems in recipes:
```
        ingredients:
        - 'mmoitem{type=MATERIAL,id=STEEL_INGOT,amount=8}'
        - 'vanilla{type=STICK,amount=4}'

```
I was trying
```
- 'customfishing{type=loot,id=fish_id,amount=1}'
- 'customfishing{type=fish_id,amount=4}'
```
Both attempts failed, recipe dont work.  
I have same issue with CustomCrops also.

**Comment by Xiao-MoMi** [comment]
mmoitems can only read mmoitems' items, so you can just solve this by using CustomFishing's MMOItems integration with loots. Just follow the wiki and set material: MMOItems:TYPE:ID, so CustomFishing would drop MMOItems items as fishing loots.
