### ISSUE TITLE
越过插件进行原版钓鱼的bug

### ISSUE THREAD

**Issue by 1392726643** [Xiao-MoMi/Custom-Fishing#21]
![屏幕截图 2024-02-13 085627](https://github.com/Xiao-MoMi/Custom-Fishing/assets/57031945/5d1316e6-b7cb-41d9-9e6f-3462247831e7)
这种钓鱼方式将大概率使插件钓鱼失效

**Comment by Xiao-MoMi** [comment]
新版本大概率修复

**Comment by Xiao-MoMi** [comment]
@1392726643 请确认是否在最新版本修复
