### ISSUE TITLE
The fishing rod hangs on the Bar, or does not appear at all. (The fishing rod comes out of fishing while the bar is being displayed..)

### ISSUE THREAD

**Issue by VacAge** [Xiao-MoMi/Custom-Fishing#6]
I installed the plugin and configured everything, but Custom-Fishing does not want to work with **MMOCore** and **MMOItems** plugins. 
The bar appears only if you set the option (instant-bar: true) All the necessary hooks are included.

Server:
- purpur-1.19.2-1858

Custom-Fishing:
- Config - [mclo.gs](https://mclo.gs/0uhdEoL)

Plugins Versions:
- MMOCore-1.11.0-SNAPSHOT
- MMOItems-6.8.3-SNAPSHOT
- MythicLib-1.4.3-SNAPSHOT
- MythicMobs-5.2.1-SNAPSHOT-4337
- mcMMO-2.1.218
- Towny-0.98.4.0
- Vault-1.7.3
- WorldGuard-7.0.8-beta-01-dist
- CustomFishing-1.2.10

Video with an error:
- [YouTube](https://youtu.be/kbUdOjIR-GY) - instant-bar: true
- [YouTube](https://youtu.be/5QytCC8Pha4) - instant-bar: false

**Comment by Xiao-MoMi** [comment]
Does MMOCore has an option to disable its fishing mechanic? Does this only happen when installing MMOCore? I need to figure out if it is a plugin conflict or not.

**Comment by VacAge** [comment]
> Owner

There is no way to disable the fishing function in MMOCore. 
You can delete a profession, when you delete a profession, mechanics is disabled and your plugin works fine, but I understand this is a compatibility problem if they cannot work together without deleting.

**Comment by Xiao-MoMi** [comment]
Latest version added custom profession name support
