### ISSUE TITLE
ERROR CONSOLE

### ISSUE THREAD

**Issue by Phoenix-99** [Xiao-MoMi/Custom-Fishing#7]
each time i catch something console show me this error:
![image](https://user-images.githubusercontent.com/63762282/208804211-4637fe59-73a4-411e-a649-c09e2c43b420.png)
and this 
![image](https://user-images.githubusercontent.com/63762282/208808802-5235e49b-a2e3-494a-8dd9-d2d6d97f91cf.png)

i think couse error when i get vanilla xp and vanilla drops from fishing

this is the  config
![image](https://user-images.githubusercontent.com/63762282/208809465-86cc8b38-35c4-4636-afe6-7ec1df9990ee.png)

**Comment by Xiao-MoMi** [comment]
use Paper instead of Spigot
